spring.application.name=${SPRING_APPLICATION_NAME:cacheservice}
server.port=${SERVER_PORT:8080}

cache.store.type=${CACHE_STORE_TYPE:redis}
cache.operation.default-lease-ms=${CACHE_DEFAULT_LEASE_MS:300000}
cache.operation.default-ttl-seconds=${CACHE_DEFAULT_TTL_SECONDS:86400}
cache.redis.key-prefix.cache=${CACHE_KEY_PREFIX_CACHE:c:}
cache.redis.key-prefix.lock=${CACHE_KEY_PREFIX_LOCK:l:}

spring.data.redis.host=${SPRING_DATA_REDIS_HOST:localhost}
spring.data.redis.port=${SPRING_DATA_REDIS_PORT:6379}
